- name: Instalando o pacote zabbix-server
  apt:
    name: zabbix-server-pgsql
    state: present

- name: Instalando o pacote zabbix-frontend-php
  apt:
    name: zabbix-frontend-php
    state: present
